### ISSUE TITLE
phpspy no longer works

### ISSUE THREAD

**Issue by eklausme** [adsr/phpspy#136] opened 2024-02-04 10:44 UTC
Program `phpspy` (v0.6.0 USE_ZEND=n COMMIT=-) no longer produces output. Invocation
```bash
$ phpspy -- php -r 'usleep(100000);'
```
gives `process_vm_readv: No such process`. While
```bash
$ phpspy -- php -r 'phpinfo();'
objdump: '/proc/13562/root//usr/bin/php': No such file
popen_read_line: No stdout; cmd=objdump -Tt '/proc/13562/root//usr/bin/php' | awk '/ executor_globals$/{print $1; exit}'
get_symbol_offset: Failed
```
Surprisingly, below seems to work:
```bash
$ phpspy -- php -r 'sleep(1);'
0 sleep <internal>:-1
1 <main> <internal>:-1

0 sleep <internal>:-1
1 <main> <internal>:-1

0 sleep <internal>:-1
1 <main> <internal>:-1
...
```

This also works (number is one million):
```bash
phpspy -- php -r 'usleep(1000000);'
```

---

Environment in use: `phpspy` is [latest version](https://github.com/adsr/phpspy/commit/5e77f5b9b9e6fb1401ba0afa6e224061c0c9885b).
```bash
$ php -v
PHP 8.3.2 (cli) (built: Jan 17 2024 14:45:51) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.2, Copyright (c) Zend Technologies
```
Linux is Arch Linux kernel `6.7.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 01 Feb 2024 10:30:35 +0000 x86_64 GNU/Linux`. I also tried with kernel `6.7.1-arch1-1`, which made no difference.

I played with setting `/proc/sys/kernel/yama/ptrace_scope` to zero or one, but that didn't change anything.

Top-like output with `-t` produces nothing:
```bash
phpspy -p 2910 -p 2908 -p 1112 -@
samp_count=0  err_count=0  func_count=0

tincl      texcl      incl       excl       excl%   func
```
This worked fine in October, see [Simplified Saaze Monitored with PHPSPY](https://eklausmeier.goip.de/blog/2023/10-29-simplified-saaze-monitored-with-phpspy), though with an older kernel and older PHP.

I also tried with an older version of PHP
```
PHP 8.2.14 (cli) (built: Dec 21 2023 14:02:51) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.14, Copyright (c) Zend Technologies
```
All are failing as above.

**Comment by adsr** [comment] 2024-02-05 04:15
Hello, thanks for the report.

> phpspy -- php -r 'usleep(100000);'

On a very slow or busy machine, or if the scheduler is acting weird, the usleep process can finish before phpspy has a chance to attach. The error you're seeing indicates such. I agree 100ms should be ample time so I'm not sure what is going on. I couldn't reproduce it on my machine. strace'ing that entire command may reveal the slow part. (Something like `strace -fvtttT ./phpspy -- php -r 'usleep(100000);'`.)

> phpspy -- php -r 'phpinfo();'

This is also a race condition. The phpinfo process finishes in the middle of phpspy trying to sort out memory addresses, hence that error. I can reproduce this.

If profiling a PHP process that lasts for only a few millis is a use-case for you, you can try something like this:

```
$ { sleep 1 && pkill -SIGCONT -x php; } & ./phpspy --rate-hz 9999 --filter-negate posix_kill -- ~/php/bin/php -r 'posix_kill(getmypid(), SIGSTOP); phpinfo();'  
[2] 750182
0 phpinfo <internal>:-1
1 <main> <internal>:-1

0 phpinfo <internal>:-1
1 <main> <internal>:-1

0 phpinfo <internal>:-1
1 <main> <internal>:-1

process_vm_readv: No such process
[1]   Exit 1                  { sleep 1 && pkill -SIGCONT -x php; }
[2]+  Done                    { sleep 1 && pkill -SIGCONT -x php; }
```

This runs phpspy with a higher sampling frequency (9999 hz) to catch fast functions. It filters out stack frames containing `posix_kill` which the php process will be stuck on for a second or so to give phpspy time to attach. The pkill process will execute after a second and allow the php process to continue. By that point phpspy is already attached and sampling, so it can maybe catch a few phpinfo stack frames. I would guess sampling very short-lived processes is a niche use case though.

It's possible the structs are wrong for that 8.2 version. I will push 8.4 structs and check against 8.2.14 and latest 8.3 this week. Please feel free to ping me again if I forget. Thank you.

**Comment by adsr** [comment] 2024-02-05 04:45
Cannot reproduce with 8.3.2 or 8.2.14, so I think this is a timing issue. If the pkill solution above works for you, that would suggest it's a timing issue as well. For now I will close this issue. We can reopen if we confirm a bug. But feel free to pastebin the strace output and I will take a look. My guess is one of the shell commands is taking a long time on your machine.

**Closed as completed by adsr** 2024-02-05 04:45 UTC

**Comment by eklausme** [comment] 2024-02-06 15:42
Thanks for quick reply!

I now run `phpspy` with `-H 9999`, which seems to alleviate the problem somewhat.

```bash
phpspy -H 9999 --pgrep=php-fpm -@
samp_count=24  err_count=4714  func_count=9

tincl      texcl      incl       excl       excl%   func
9          5          0          0          0.00    FFI::string <internal>:-1
4          4          0          0          0.00    strpos <internal>:-1
3          3          0          0          0.00    str_replace <internal>:-1
3          3          0          0          0.00    substr <internal>:-1
2          2          0          0          0.00    ctype_space <internal>:-1
2          2          0          0          0.00    max <internal>:-1
2          2          0          0          0.00    is_dir <internal>:-1
2          2          0          0          0.00    <main> <internal>:-1
1          1          0          0          0.00    defined <internal>:-1
```
err_count being quite high.

It is crucial to set:
```bash
echo 0 > /proc/sys/kernel/yama/ptrace_scope
```

---

## Version check

I checked on an "older" machine `6.5.3-arch1-1`, where I hadn't updated for some time:
```bash
PHP 8.2.10 (cli) (built: Sep  1 2023 11:07:36) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.10, Copyright (c) Zend Technologies
```
Problem is the same: no output from _long-running_ process.

I was not interested in profiling short running PHP programs. I used the `usleep()` example, as this is given in the documentation. The main goal was to profile long-running `php-fpm` processes. They had accumulated some CPU time, see [Simplified Saaze Monitored with PHPSPY](https://eklausmeier.goip.de/blog/2023/10-29-simplified-saaze-monitored-with-phpspy) from October and December 2023:
```
phpspy -p 940 -p 17132 -p 61898 -p 61899 -@
samp_count=666  err_count=10  func_count=67

tincl      texcl      incl       excl       excl%   func
313        151        0          0          0.00    ComposerAutoloaderInit50920a90746408ba7a500bacdb4908c1::getLoader /home/klm/php/sndsaaze/vendor/composer/autoload_real.php:19
132        103        0          0          0.00    composerRequire50920a90746408ba7a500bacdb4908c1 /home/klm/php/sndsaaze/vendor/composer/autoload_real.php:50
99         99         0          0          0.00    Composer\Autoload\includeFile /home/klm/php/sndsaaze/vendor/composer/ClassLoader.php:569
76         76         0          0          0.00    json_decode <internal>:-1
298        34         0          0          0.00    Saaze\Saaze::run /home/klm/php/sndsaaze/vendor/eklausme/saaze/Saaze.php:32
30         30         0          0          0.00    ComposerAutoloaderInit50920a90746408ba7a500bacdb4908c1::loadClassLoader /home/klm/php/sndsaaze/vendor/composer/autoload_real.php:9
23         23         0          0          0.00    FFI::cdef <internal>:-1
```
The interesting part, that `phpspy` brought up at that time, was, that composer was quite dominant. I didn't expect that.  The JSON processing was expected.

I changed accordingly and now wanted to confirm that these times are no longer present.


## Error messages

These errors are something like:
```bash
phpspy --pgrep=php-fpm
copy_proc_mem: Failed to copy filename; err=Bad address raddr=0xf00000001 size=25
copy_proc_mem: Failed to copy filename; err=Bad address raddr=0xf00000001 size=25
copy_proc_mem: Failed to copy filename; err=Bad address raddr=0x29e00000232 size=25
copy_proc_mem: Failed to copy filename; err=Bad address raddr=0x2a00000013 size=25
copy_proc_mem: Failed to copy filename; err=Bad address raddr=0x23c00000239 size=25
```
Occasionally I also see
```
copy_proc_mem: Failed to copy zfunc; err=Bad address raddr=0x7ec300000106 size=164
calc_sleep_time: Expected sleep_ns>0; decrease sample rate
```

None of the machines involved is busy: `load average: 0.19, 0.23, 0.18`.

Maybe below versions might be of interest.

Name | version
---|---
glibc | 2.28-3
glibc | 2.38-7
glibc | 2.39-1
